apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      annotations:
        checksum/grafana-datasources: 48faab41f579fc8efde6034391496f6a
      labels:
        app: grafana
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: "managed-ng-private"
      containers:
      - env: []
        image: grafana/grafana:7.1.0
        name: grafana
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
          readOnly: false
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - name: grafana-dashboard-jitsi
          mountPath: /grafana-dashboard-definitions/0/jitsi
          readOnly: false
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: grafana
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - name: grafana-datasources
        secret:
          secretName: grafana-datasources
      - configMap:
          name: grafana-dashboard-jitsi
        name: grafana-dashboard-jitsi
      - configMap:
          name: grafana-dashboards
        name: grafana-dashboards
