apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: haproxy-pod-monitor
  namespace: production
spec:
  selector:
    matchLabels:
      k8s-app: haproxy
  namespaceSelector:
    any: false
    matchNames:
      - production
  podMetricsEndpoints:
    - port: metrics
