apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jvb-pod-monitor
  namespace: public
spec:
  selector:
    matchLabels:
      k8s-app: jvb
  namespaceSelector:
    any: false
    matchNames:
      - public
  podMetricsEndpoints:
    - port: metrics
