apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jvb-pod-monitor
  namespace: public
spec:
  selector:
    matchLabels:
      app: jvb
  podMetricsEndpoints:
    - port: metrics
