apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-dashboardDatasources.yaml
  - grafana-dashboardDefinitions.yaml
  - grafana-system-dashboardDefinitions.yaml
  - grafana-dashboardSources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-serviceAccount.yaml
  - kube-state-metrics-clusterRole.yaml
  - kube-state-metrics-clusterRoleBinding.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-service.yaml
  - kube-state-metrics-serviceAccount.yaml
  - node-exporter-clusterRole.yaml
  - node-exporter-clusterRoleBinding.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-prometheusRule.yaml
  - node-exporter-service.yaml
  - node-exporter-serviceAccount.yaml
  - node-exporter-serviceMonitor.yaml
  - prometheus-adapter-apiService.yaml
  - prometheus-adapter-clusterRole.yaml
  - prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - prometheus-adapter-clusterRoleBinding.yaml
  - prometheus-adapter-clusterRoleBindingDelegator.yaml
  - prometheus-adapter-clusterRoleServerResources.yaml
  - prometheus-adapter-configMap.yaml
  - prometheus-adapter-deployment.yaml
  - prometheus-adapter-roleBindingAuthReader.yaml
  - prometheus-adapter-service.yaml
  - prometheus-adapter-serviceAccount.yaml
  - prometheus-clusterRole.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-prometheus.yaml
  - prometheus-roleBindingConfig.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleConfig.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-service.yaml
  - prometheus-serviceAccount.yaml
  - 0namespace-namespace.yaml
  - setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  - setup/prometheus-operator-0podmonitorCustomResourceDefinition.yaml
  - setup/prometheus-operator-0probeCustomResourceDefinition.yaml
  - setup/prometheus-operator-0prometheusCustomResourceDefinition.yaml
  - setup/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  - setup/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
  - setup/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
  - setup/prometheus-operator-clusterRole.yaml
  - setup/prometheus-operator-clusterRoleBinding.yaml
  - setup/prometheus-operator-deployment.yaml
  - setup/prometheus-operator-service.yaml
  - setup/prometheus-operator-serviceAccount.yaml
  - haproxy-pod-monitor.yaml
  - prosody-pod-monitor.yaml
  - jvb-pod-monitor.yaml
  - jicofo-pod-monitor.yaml
  - pricing-service-pod-monitor.yaml
  - alertmanager-alertmanager.yaml
  - alertmanager-podDisruptionBudget.yaml
  - alertmanager-prometheusRule.yaml
  - alertmanager-secret.yaml
  - alertmanager-service.yaml
  - alertmanager-serviceAccount.yaml
  - alertmanager-serviceMonitor.yaml
  - grafana-pvc.yaml
