apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pricing-service-pod-monitor
  namespace: production
spec:
  selector:
    matchLabels:
      app: pricing-service
  namespaceSelector:
    any: false
    matchNames:
      - production     
  podMetricsEndpoints:
    - port: 9002