apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP